services:
    db:
      image: postgres:14.5
      environment:
        POSTGRES_PASSWORD: example

    frontend:
      build: 
        context: ./frontend
        dockerfile: ./Dockerfile.frontend
      ports:
        - "4000:4000"



