FROM python:3.11-alpine
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt psycopg2-binary pandas requests

ENV FLASK_RUN run.py
ENV FLASK_ENV development
ENV FLASK_RUN_PORT 8000
ENV FLASK_RUN_HOST 0.0.0.0

EXPOSE 8000
CMD ["flask", "run"]
